### ISSUE TITLE
Erro na classe 'Controlar Cliente'

### ISSUE THREAD

**Issue by sostenesg7** [MatthewMartins/Repositorio_GP_OffStation#1]
**Está tentando passar um objeto Cliente para a super Classe, mas a classe atual não herda de  nenhuma classe que peça um Cliente no construtor.**

_Erro: Linha 11, arquivo ControlarCliente.java.
Dica: Remover o parâmetro passado para a Super Classe._

> C:\Users\Sostenes\Documents\NetBeansProjects\Repositorio_GP_OffStation\ProjetoGP_OffStation\src\projetos\gerencia\apresentacao\ControlarCliente.java:11: error: cannot find symbol
>         super(new Cliente(nome, sobrenome, email));
>   symbol:   class Cliente
>   location: class ControlarCliente

**Comment by luanupe** [comment]
ah sim, obrigado por lembrar, inclusive eu já tinha percebido o erro e corrigi, só dar um pull para atualizar seus arquivos.

**Comment by luanupe** [comment]
Para evitar classes redundantes eu coloquei o método salvar para passar "diretamente" as informações e/ou objeto, os valores não serão mais passados pelo construtor, nos métodos de controle também é possível recuperar as informações.

Adicionei também o que você tinha pedido pra recuperar os produtos pelo nome, está retornando um HashMap<Integer, IProduto> onde o valor Integer é o id do produto.

**Comment by wylliams** [comment]
Boa pessoal! Vamos manter o pace!
